#include "BindingLayerGenerator.h"
#include "DataSource.h"
#include "DataBinding.h"

namespace CodeGen {

QString BindingLayerGenerator::generateBindingsHeader(const Project* project) {
    Q_UNUSED(project);
    QString code;
    code += "/**\n";
    code += " * @file ui_bindings.h\n";
    code += " * @brief Runtime Data Binding Layer for UI Components & DataSources\n";
    code += " * Auto-generated by Embedded UI Designer\n";
    code += " */\n\n";
    code += "#ifndef UI_BINDINGS_H\n";
    code += "#define UI_BINDINGS_H\n\n";
    code += "#include <stdint.h>\n";
    code += "#include <stdbool.h>\n\n";
    code += "#ifdef __cplusplus\n";
    code += "extern \"C\" {\n";
    code += "#endif\n\n";

    code += "/* Initialize Data Bindings and subscribe to hardware changes */\n";
    code += "void ui_bindings_init(void);\n\n";

    code += "/* Periodic Data Source Update Loop (call every ~50ms in main task loop) */\n";
    code += "void ui_update_data_sources(void);\n\n";

    code += "/* Output Write Dispatcher (invoked when interactive widgets mutate) */\n";
    code += "void ui_write_data_source(const char* source_id, float value);\n\n";

    code += "#ifdef __cplusplus\n";
    code += "}\n";
    code += "#endif\n\n";
    code += "#endif /* UI_BINDINGS_H */\n";
    return code;
}

QString BindingLayerGenerator::generateBindingsSource(const Project* project) {
    QString code;
    code += "/**\n";
    code += " * @file ui_bindings.c\n";
    code += " * @brief Runtime Data Binding Implementation\n";
    code += " * Auto-generated by Embedded UI Designer\n";
    code += " */\n\n";
    code += "#include \"ui_bindings.h\"\n";
    code += "#include \"ui.h\"\n";
    code += "#include \"target_hal.h\"\n";
    code += "#include <stdio.h>\n";
    code += "#include <string.h>\n\n";

    code += "void ui_bindings_init(void) {\n";
    code += "    target_hal_init();\n";
    code += "    printf(\"[UI BINDINGS] Initialized data binding pipeline.\\n\");\n";
    code += "}\n\n";

    code += "void ui_update_data_sources(void) {\n";
    if (project) {
        for (const auto& b : project->dataBindings()) {
            const DataSource* ds = project->findDataSource(b.sourceId());
            if (!ds) continue;

            QString compId = b.componentId();
            QString prop = b.propertyName().toLower();
            QString ref = ds->hardwareRef().isEmpty() ? ds->id() : ds->hardwareRef();

            if (b.direction() == BindingDirection::Read || b.direction() == BindingDirection::ReadWrite) {
                if (ds->type() == DataSourceType::Adc || ds->type() == DataSourceType::Sensor) {
                    code += QString("    /* Binding: %1.%2 <- DataSource '%3' */\n").arg(compId, prop, ds->id());
                    code += QString("    float val_%1 = hal_read_adc_normalized(\"%2\");\n").arg(compId, ref);
                    code += QString("    #ifdef LV_OBJ_H\n");
                    code += QString("    if (ui_bar_%1) lv_bar_set_value(ui_bar_%1, (int32_t)(val_%1 * 100.0f), LV_ANIM_OFF);\n").arg(compId);
                    code += QString("    if (ui_arc_%1) lv_arc_set_value(ui_arc_%1, (int32_t)(val_%1 * 100.0f));\n").arg(compId);
                    code += QString("    #endif\n\n");
                } else if (ds->type() == DataSourceType::Gpio) {
                    code += QString("    /* Binding: %1.%2 <- GPIO '%3' */\n").arg(compId, prop, ds->id());
                    code += QString("    bool state_%1 = hal_read_digital_pin(\"%2\");\n").arg(compId, ref);
                    code += QString("    #ifdef LV_OBJ_H\n");
                    code += QString("    if (ui_sw_%1) {\n").arg(compId);
                    code += QString("        if (state_%1) lv_obj_add_state(ui_sw_%1, LV_STATE_CHECKED);\n").arg(compId);
                    code += QString("        else lv_obj_clear_state(ui_sw_%1, LV_STATE_CHECKED);\n");
                    code += "    }\n";
                    code += QString("    #endif\n\n");
                }
            }
        }
    }
    code += "}\n\n";

    code += "void ui_write_data_source(const char* source_id, float value) {\n";
    code += "    if (!source_id) return;\n";
    if (project) {
        for (const auto& b : project->dataBindings()) {
            if (b.direction() == BindingDirection::Write || b.direction() == BindingDirection::ReadWrite) {
                const DataSource* ds = project->findDataSource(b.sourceId());
                if (!ds) continue;
                QString ref = ds->hardwareRef().isEmpty() ? ds->id() : ds->hardwareRef();
                code += QString("    if (strcmp(source_id, \"%1\") == 0) {\n").arg(ds->id());
                if (ds->type() == DataSourceType::Gpio) {
                    code += QString("        hal_write_digital_pin(\"%1\", value > 0.5f);\n").arg(ref);
                } else if (ds->type() == DataSourceType::Pwm) {
                    code += QString("        hal_write_pwm_duty(\"%1\", value);\n").arg(ref);
                }
                code += "        return;\n";
                code += "    }\n";
            }
        }
    }
    code += "    printf(\"[UI BINDINGS] Unhandled write for DataSource: %s\\n\", source_id);\n";
    code += "}\n";

    return code;
}

QString BindingLayerGenerator::generateQulBindings(const Project* project) {
    QString code;
    code += "// Qt for MCUs (QUL) Data Binding Definitions\n";
    code += "import QtQuick 2.15\n\n";
    code += "Item {\n";
    code += "    id: rootBindings\n\n";

    if (project) {
        for (const auto& ds : project->dataSources()) {
            QString typeStr = (ds.dataType() == DataType::Boolean) ? "bool" : "real";
            QString defaultVal = (ds.dataType() == DataType::Boolean) ? "false" : "0.0";
            code += QString("    property %1 ds_%2: %3\n").arg(typeStr, ds.id(), defaultVal);
        }
    }

    code += "}\n";
    return code;
}

} // namespace CodeGen
