#include "TargetHalGenerator.h"

namespace CodeGen {

QString TargetHalGenerator::generateHalHeader(const Project* project) {
    QString fam = project ? project->hardwareConfig().family : "STM32";
    QString board = project ? project->hardwareConfig().boardId : "Generic";

    QString code;
    code += "/**\n";
    code += " * @file target_hal.h\n";
    code += " * @brief Target Hardware Abstraction Layer Adapter\n";
    code += QString(" * Target Family: %1 | Target Board: %2\n").arg(fam, board);
    code += " * Auto-generated by Embedded UI Designer (Phase 4 Code Generator v2)\n";
    code += " */\n\n";
    code += "#ifndef TARGET_HAL_H\n";
    code += "#define TARGET_HAL_H\n\n";
    code += "#include <stdint.h>\n";
    code += "#include <stdbool.h>\n\n";
    code += "#ifdef __cplusplus\n";
    code += "extern \"C\" {\n";
    code += "#endif\n\n";

    code += "/* HAL Initialization */\n";
    code += "void target_hal_init(void);\n\n";

    code += "/* Digital GPIO */\n";
    code += "bool hal_read_digital_pin(const char* pin_name);\n";
    code += "void hal_write_digital_pin(const char* pin_name, bool high);\n\n";

    code += "/* Analog ADC (Returns raw 12-bit / 16-bit count and normalized float 0.0 - 1.0) */\n";
    code += "uint32_t hal_read_adc_raw(const char* pin_name);\n";
    code += "float hal_read_adc_normalized(const char* pin_name);\n\n";

    code += "/* PWM Output */\n";
    code += "void hal_write_pwm_duty(const char* pin_name, float duty_percent);\n\n";

    code += "/* Sensor Readouts */\n";
    code += "float hal_read_sensor_value(const char* sensor_name);\n\n";

    code += "#ifdef __cplusplus\n";
    code += "}\n";
    code += "#endif\n\n";
    code += "#endif /* TARGET_HAL_H */\n";
    return code;
}

QString TargetHalGenerator::generateHalSource(const Project* project) {
    QString fam = project ? project->hardwareConfig().family : "STM32";
    QString board = project ? project->hardwareConfig().boardId : "Generic";

    QString code;
    code += "/**\n";
    code += " * @file target_hal.c\n";
    code += " * @brief Target Hardware Abstraction Layer Adapter Implementation\n";
    code += QString(" * Target Family: %1 | Target Board: %2\n").arg(fam, board);
    code += " * Auto-generated by Embedded UI Designer\n";
    code += " */\n\n";
    code += "#include \"target_hal.h\"\n";
    code += "#include <stdio.h>\n";
    code += "#include <string.h>\n\n";

    if (fam.compare("STM32", Qt::CaseInsensitive) == 0) {
        code += "/* STM32 Target Hardware Drivers (HAL / CMSIS) */\n";
        code += "void target_hal_init(void) {\n";
        code += "    printf(\"[HAL: STM32] Initializing GPIO clocks & ADC peripheral...\\n\");\n";
        code += "    /* __HAL_RCC_GPIOA_CLK_ENABLE(); */\n";
        code += "    /* __HAL_RCC_GPIOB_CLK_ENABLE(); */\n";
        code += "    /* __HAL_RCC_GPIOC_CLK_ENABLE(); */\n";
        code += "}\n\n";

        code += "bool hal_read_digital_pin(const char* pin_name) {\n";
        code += "    (void)pin_name;\n";
        code += "    /* return (GPIOA->IDR & (1 << pin_num)) != 0; */\n";
        code += "    return false;\n";
        code += "}\n\n";

        code += "void hal_write_digital_pin(const char* pin_name, bool high) {\n";
        code += "    printf(\"[HAL: STM32] Atomic BSRR Write pin %s -> %s\\n\", pin_name, high ? \"HIGH (1)\" : \"LOW (0)\");\n";
        code += "    /* GPIOA->BSRR = high ? (1 << pin_num) : (1 << (pin_num + 16)); */\n";
        code += "}\n\n";

        code += "uint32_t hal_read_adc_raw(const char* pin_name) {\n";
        code += "    (void)pin_name;\n";
        code += "    /* return HAL_ADC_GetValue(&hadc1); */\n";
        code += "    return 2048;\n";
        code += "}\n\n";

        code += "float hal_read_adc_normalized(const char* pin_name) {\n";
        code += "    uint32_t raw = hal_read_adc_raw(pin_name);\n";
        code += "    return (float)raw / 4095.0f;\n";
        code += "}\n\n";

        code += "void hal_write_pwm_duty(const char* pin_name, float duty_percent) {\n";
        code += "    printf(\"[HAL: STM32] Set Timer PWM on %s to %.1f%%\\n\", pin_name, duty_percent);\n";
        code += "}\n\n";

        code += "float hal_read_sensor_value(const char* sensor_name) {\n";
        code += "    (void)sensor_name;\n";
        code += "    return 72.5f;\n";
        code += "}\n";
    } else if (fam.compare("ESP32", Qt::CaseInsensitive) == 0) {
        code += "/* ESP32 Target Hardware Drivers (ESP-IDF) */\n";
        code += "void target_hal_init(void) {\n";
        code += "    printf(\"[HAL: ESP32] Initializing ESP32 GPIOs and ADC oneshot driver...\\n\");\n";
        code += "}\n\n";

        code += "bool hal_read_digital_pin(const char* pin_name) {\n";
        code += "    (void)pin_name;\n";
        code += "    return false;\n";
        code += "}\n\n";

        code += "void hal_write_digital_pin(const char* pin_name, bool high) {\n";
        code += "    printf(\"[HAL: ESP32] gpio_set_level(%s, %d)\\n\", pin_name, high ? 1 : 0);\n";
        code += "}\n\n";

        code += "uint32_t hal_read_adc_raw(const char* pin_name) {\n";
        code += "    (void)pin_name;\n";
        code += "    return 2048;\n";
        code += "}\n\n";

        code += "float hal_read_adc_normalized(const char* pin_name) {\n";
        code += "    return (float)hal_read_adc_raw(pin_name) / 4095.0f;\n";
        code += "}\n\n";

        code += "void hal_write_pwm_duty(const char* pin_name, float duty_percent) {\n";
        code += "    printf(\"[HAL: ESP32] ledc_set_duty(%s, %.1f%%)\\n\", pin_name, duty_percent);\n";
        code += "}\n\n";

        code += "float hal_read_sensor_value(const char* sensor_name) {\n";
        code += "    (void)sensor_name;\n";
        code += "    return 25.0f;\n";
        code += "}\n";
    } else {
        code += "/* Generic / Linux / PC Simulator Target HAL Driver */\n";
        code += "void target_hal_init(void) {\n";
        code += "    printf(\"[HAL: Generic] Target hardware abstraction initialized.\\n\");\n";
        code += "}\n\n";

        code += "bool hal_read_digital_pin(const char* pin_name) {\n";
        code += "    (void)pin_name;\n";
        code += "    return false;\n";
        code += "}\n\n";

        code += "void hal_write_digital_pin(const char* pin_name, bool high) {\n";
        code += "    printf(\"[HAL: Generic] Write pin %s -> %s\\n\", pin_name, high ? \"HIGH (1)\" : \"LOW (0)\");\n";
        code += "}\n\n";

        code += "uint32_t hal_read_adc_raw(const char* pin_name) {\n";
        code += "    (void)pin_name;\n";
        code += "    return 2048;\n";
        code += "}\n\n";

        code += "float hal_read_adc_normalized(const char* pin_name) {\n";
        code += "    return 0.5f;\n";
        code += "}\n\n";

        code += "void hal_write_pwm_duty(const char* pin_name, float duty_percent) {\n";
        code += "    printf(\"[HAL: Generic] PWM duty on %s -> %.1f%%\\n\", pin_name, duty_percent);\n";
        code += "}\n\n";

        code += "float hal_read_sensor_value(const char* sensor_name) {\n";
        code += "    (void)sensor_name;\n";
        code += "    return 50.0f;\n";
        code += "}\n";
    }

    return code;
}

} // namespace CodeGen
