#include "ImageAssetProcessor.h"
#include <QColor>
#include <QTextStream>

QByteArray ImageAssetProcessor::processToBytes(const QImage& image, ImageFormat format) {
    QByteArray bytes;
    if (image.isNull()) return bytes;

    const int width = image.width();
    const int height = image.height();

    // Ensure we are working with an RGB32 representation for consistent pixel extraction
    QImage converted = image.convertToFormat(QImage::Format_ARGB32);

    switch (format) {
        case ImageFormat::RGB565: {
            bytes.reserve(width * height * 2);
            for (int y = 0; y < height; ++y) {
                const QRgb* scanline = reinterpret_cast<const QRgb*>(converted.constScanLine(y));
                for (int x = 0; x < width; ++x) {
                    QRgb pixel = scanline[x];
                    int r = qRed(pixel);
                    int g = qGreen(pixel);
                    int b = qBlue(pixel);

                    // 16-bit RGB565: R[4:0] (5 bits), G[5:0] (6 bits), B[4:0] (5 bits)
                    uint16_t rgb565 = static_cast<uint16_t>(
                        ((r >> 3) << 11) |
                        ((g >> 2) << 5)  |
                        (b >> 3)
                    );

                    // Output as big-endian (MSB first) standard for embedded display controllers
                    bytes.append(static_cast<char>((rgb565 >> 8) & 0xFF));
                    bytes.append(static_cast<char>(rgb565 & 0xFF));
                }
            }
            break;
        }

        case ImageFormat::Monochrome: {
            // 1-bit thresholding: 8 horizontal pixels per byte
            int rowBytes = (width + 7) / 8;
            bytes.reserve(rowBytes * height);

            for (int y = 0; y < height; ++y) {
                const QRgb* scanline = reinterpret_cast<const QRgb*>(converted.constScanLine(y));
                uint8_t currentByte = 0;
                int bitIndex = 0;

                for (int x = 0; x < width; ++x) {
                    QRgb pixel = scanline[x];
                    int r = qRed(pixel);
                    int g = qGreen(pixel);
                    int b = qBlue(pixel);

                    // ITU-R BT.601 standard luminance calculation
                    int luminance = qRound(0.299 * r + 0.587 * g + 0.114 * b);
                    bool isWhite = (luminance >= 128);

                    if (isWhite) {
                        currentByte |= (1 << (7 - bitIndex));
                    }

                    bitIndex++;
                    if (bitIndex == 8) {
                        bytes.append(static_cast<char>(currentByte));
                        currentByte = 0;
                        bitIndex = 0;
                    }
                }

                // If scanline length is not a multiple of 8, flush the remaining bits padded with zeros
                if (bitIndex > 0) {
                    bytes.append(static_cast<char>(currentByte));
                }
            }
            break;
        }

        case ImageFormat::RGB888: {
            bytes.reserve(width * height * 3);
            for (int y = 0; y < height; ++y) {
                const QRgb* scanline = reinterpret_cast<const QRgb*>(converted.constScanLine(y));
                for (int x = 0; x < width; ++x) {
                    QRgb pixel = scanline[x];
                    bytes.append(static_cast<char>(qRed(pixel)));
                    bytes.append(static_cast<char>(qGreen(pixel)));
                    bytes.append(static_cast<char>(qBlue(pixel)));
                }
            }
            break;
        }
    }

    return bytes;
}

QString ImageAssetProcessor::generateCArray(const QImage& image, ImageFormat format, const QString& arrayName) {
    if (image.isNull()) {
        return QString("// Error: Image is null or empty\n");
    }

    QByteArray rawBytes = processToBytes(image, format);
    QString formatStr;
    switch (format) {
        case ImageFormat::RGB565: formatStr = "RGB565 (16-bit color, 2 bytes/pixel)"; break;
        case ImageFormat::Monochrome: formatStr = "Monochrome (1-bit thresholding, 8 pixels/byte)"; break;
        case ImageFormat::RGB888: formatStr = "RGB888 (24-bit color, 3 bytes/pixel)"; break;
    }

    QString result;
    QTextStream out(&result);

    out << "/*\n";
    out << " * Embedded Image Asset: " << arrayName << "\n";
    out << " * Dimensions: " << image.width() << " x " << image.height() << " px\n";
    out << " * Format: " << formatStr << "\n";
    out << " * Total Size: " << rawBytes.size() << " bytes\n";
    out << " * Auto-generated by EmbeddedUIDesigner Asset Compilation Pipeline\n";
    out << " */\n";
    out << "#include <stdint.h>\n";
    out << "#include <stddef.h>\n\n";
    out << "const uint32_t " << arrayName << "_width = " << image.width() << ";\n";
    out << "const uint32_t " << arrayName << "_height = " << image.height() << ";\n";
    out << "const size_t " << arrayName << "_size = " << rawBytes.size() << ";\n\n";
    out << "const uint8_t " << arrayName << "[] = {\n";

    const int bytesPerLine = 12;
    for (int i = 0; i < rawBytes.size(); ++i) {
        if (i % bytesPerLine == 0) {
            out << "    ";
        }

        uint8_t b = static_cast<uint8_t>(rawBytes.at(i));
        out << "0x" << QString("%1").arg(b, 2, 16, QChar('0')).toUpper();

        if (i < rawBytes.size() - 1) {
            out << ", ";
        }

        if ((i + 1) % bytesPerLine == 0 || i == rawBytes.size() - 1) {
            out << "\n";
        }
    }

    out << "};\n";
    return result;
}
